chore(ci): add rust-cache to rust workflow

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -40,9 +40,18 @@ jobs:
         with:
           targets: ${{ matrix.target }}
 
+      - name: Cache Deps & Bins
+        uses: Swatinem/rust-cache@v2
+
       - name: Install cross
         shell: bash
-        run: cargo install cross --git https://github.com/cross-rs/cross
+        run: |
+          if ! command -v cross &> /dev/null; then
+            echo "cross not found, installing..."
+            cargo install cross --git https://github.com/cross-rs/cross
+          else
+            echo "cross already installed, skipping installation."
+          fi
 
       - name: Build - ${{ matrix.target }}
         shell: bash
